/**
 * @file Supabase schema
 *
 * This file is automatically generated by npm run supabase:schema. DO NOT EDIT THIS FILE!
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | {[key: string]: Json | undefined}
  | Json[];

export type Database = {
  public: {
    Tables: {
      comment_reports: {
        Row: {
          comment_id: string;
          created_at: string;
          id: string;
          reporter_id: string;
        };
        Insert: {
          comment_id: string;
          created_at?: string;
          id?: string;
          reporter_id?: string;
        };
        Update: {
          comment_id?: string;
          created_at?: string;
          id?: string;
          reporter_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "comment_reports_comment_id_fkey";
            columns: ["comment_id"];
            isOneToOne: false;
            referencedRelation: "comments";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "comment_reports_comment_id_fkey";
            columns: ["comment_id"];
            isOneToOne: false;
            referencedRelation: "personalized_comments";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "comment_reports_reporter_id_fkey";
            columns: ["reporter_id"];
            isOneToOne: false;
            referencedRelation: "users";
            referencedColumns: ["id"];
          },
        ];
      };
      comment_views: {
        Row: {
          comment_id: string;
          created_at: string;
          id: string;
          viewer_id: string;
        };
        Insert: {
          comment_id: string;
          created_at?: string;
          id?: string;
          viewer_id?: string;
        };
        Update: {
          comment_id?: string;
          created_at?: string;
          id?: string;
          viewer_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "comment_views_comment_id_fkey";
            columns: ["comment_id"];
            isOneToOne: false;
            referencedRelation: "comments";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "comment_views_comment_id_fkey";
            columns: ["comment_id"];
            isOneToOne: false;
            referencedRelation: "personalized_comments";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "comment_views_viewer_id_fkey";
            columns: ["viewer_id"];
            isOneToOne: false;
            referencedRelation: "users";
            referencedColumns: ["id"];
          },
        ];
      };
      comment_votes: {
        Row: {
          comment_id: string;
          created_at: string;
          id: string;
          upvote: boolean;
          voter_id: string;
        };
        Insert: {
          comment_id: string;
          created_at?: string;
          id?: string;
          upvote: boolean;
          voter_id?: string;
        };
        Update: {
          comment_id?: string;
          created_at?: string;
          id?: string;
          upvote?: boolean;
          voter_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "comment_votes_comment_id_fkey";
            columns: ["comment_id"];
            isOneToOne: false;
            referencedRelation: "comments";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "comment_votes_comment_id_fkey";
            columns: ["comment_id"];
            isOneToOne: false;
            referencedRelation: "personalized_comments";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "comment_votes_voter_id_fkey";
            columns: ["voter_id"];
            isOneToOne: false;
            referencedRelation: "users";
            referencedColumns: ["id"];
          },
        ];
      };
      comments: {
        Row: {
          commenter_id: string | null;
          content: string;
          created_at: string;
          downvotes: number;
          id: string;
          parent_id: string | null;
          post_id: string;
          private_anonymous: boolean;
          private_commenter_id: string;
          upvotes: number;
          views: number;
        };
        Insert: {
          commenter_id?: string | null;
          content: string;
          created_at?: string;
          downvotes?: number;
          id?: string;
          parent_id?: string | null;
          post_id: string;
          private_anonymous?: boolean;
          private_commenter_id?: string;
          upvotes?: number;
          views?: number;
        };
        Update: {
          commenter_id?: string | null;
          content?: string;
          created_at?: string;
          downvotes?: number;
          id?: string;
          parent_id?: string | null;
          post_id?: string;
          private_anonymous?: boolean;
          private_commenter_id?: string;
          upvotes?: number;
          views?: number;
        };
        Relationships: [
          {
            foreignKeyName: "comments_parent_id_fkey";
            columns: ["parent_id"];
            isOneToOne: false;
            referencedRelation: "comments";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "comments_parent_id_fkey";
            columns: ["parent_id"];
            isOneToOne: false;
            referencedRelation: "personalized_comments";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "comments_post_id_fkey";
            columns: ["post_id"];
            isOneToOne: false;
            referencedRelation: "personalized_posts";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "comments_post_id_fkey";
            columns: ["post_id"];
            isOneToOne: false;
            referencedRelation: "posts";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "comments_private_commenter_id_fkey";
            columns: ["private_commenter_id"];
            isOneToOne: false;
            referencedRelation: "users";
            referencedColumns: ["id"];
          },
        ];
      };
      locations: {
        Row: {
          created_at: string;
          id: string;
          location: unknown;
          user_id: string;
        };
        Insert: {
          created_at?: string;
          id?: string;
          location: unknown;
          user_id?: string;
        };
        Update: {
          created_at?: string;
          id?: string;
          location?: unknown;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "locations_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "users";
            referencedColumns: ["id"];
          },
        ];
      };
      post_reports: {
        Row: {
          created_at: string;
          id: string;
          post_id: string;
          reporter_id: string;
        };
        Insert: {
          created_at?: string;
          id?: string;
          post_id: string;
          reporter_id?: string;
        };
        Update: {
          created_at?: string;
          id?: string;
          post_id?: string;
          reporter_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "post_reports_post_id_fkey";
            columns: ["post_id"];
            isOneToOne: false;
            referencedRelation: "personalized_posts";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "post_reports_post_id_fkey";
            columns: ["post_id"];
            isOneToOne: false;
            referencedRelation: "posts";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "post_reports_reporter_id_fkey";
            columns: ["reporter_id"];
            isOneToOne: false;
            referencedRelation: "users";
            referencedColumns: ["id"];
          },
        ];
      };
      post_views: {
        Row: {
          created_at: string;
          id: string;
          post_id: string;
          viewer_id: string;
        };
        Insert: {
          created_at?: string;
          id?: string;
          post_id: string;
          viewer_id?: string;
        };
        Update: {
          created_at?: string;
          id?: string;
          post_id?: string;
          viewer_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "post_views_post_id_fkey";
            columns: ["post_id"];
            isOneToOne: false;
            referencedRelation: "personalized_posts";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "post_views_post_id_fkey";
            columns: ["post_id"];
            isOneToOne: false;
            referencedRelation: "posts";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "post_views_viewer_id_fkey";
            columns: ["viewer_id"];
            isOneToOne: false;
            referencedRelation: "users";
            referencedColumns: ["id"];
          },
        ];
      };
      post_votes: {
        Row: {
          created_at: string;
          id: string;
          post_id: string;
          upvote: boolean;
          voter_id: string;
        };
        Insert: {
          created_at?: string;
          id?: string;
          post_id: string;
          upvote: boolean;
          voter_id?: string;
        };
        Update: {
          created_at?: string;
          id?: string;
          post_id?: string;
          upvote?: boolean;
          voter_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "post_votes_post_id_fkey";
            columns: ["post_id"];
            isOneToOne: false;
            referencedRelation: "personalized_posts";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "post_votes_post_id_fkey";
            columns: ["post_id"];
            isOneToOne: false;
            referencedRelation: "posts";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "post_votes_voter_id_fkey";
            columns: ["voter_id"];
            isOneToOne: false;
            referencedRelation: "users";
            referencedColumns: ["id"];
          },
        ];
      };
      posts: {
        Row: {
          aspect_ratio: number | null;
          blur_hash: string | null;
          comments: number;
          content: string;
          created_at: string;
          downvotes: number;
          has_media: boolean;
          id: string;
          poster_id: string | null;
          private_anonymous: boolean;
          private_location: unknown;
          private_poster_id: string;
          radius: number;
          upvotes: number;
          views: number;
        };
        Insert: {
          aspect_ratio?: number | null;
          blur_hash?: string | null;
          comments?: number;
          content: string;
          created_at?: string;
          downvotes?: number;
          has_media?: boolean;
          id?: string;
          poster_id?: string | null;
          private_anonymous?: boolean;
          private_location?: unknown;
          private_poster_id?: string;
          radius: number;
          upvotes?: number;
          views?: number;
        };
        Update: {
          aspect_ratio?: number | null;
          blur_hash?: string | null;
          comments?: number;
          content?: string;
          created_at?: string;
          downvotes?: number;
          has_media?: boolean;
          id?: string;
          poster_id?: string | null;
          private_anonymous?: boolean;
          private_location?: unknown;
          private_poster_id?: string;
          radius?: number;
          upvotes?: number;
          views?: number;
        };
        Relationships: [
          {
            foreignKeyName: "posts_private_poster_id_fkey";
            columns: ["private_poster_id"];
            isOneToOne: false;
            referencedRelation: "users";
            referencedColumns: ["id"];
          },
        ];
      };
      profiles: {
        Row: {
          color: string;
          emoji: string;
          id: string;
        };
        Insert: {
          color?: string;
          emoji?: string;
          id: string;
        };
        Update: {
          color?: string;
          emoji?: string;
          id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "profiles_id_fkey";
            columns: ["id"];
            isOneToOne: true;
            referencedRelation: "users";
            referencedColumns: ["id"];
          },
        ];
      };
    };
    Views: {
      personalized_comments: {
        Row: {
          commenter_color: string | null;
          commenter_emoji: string | null;
          commenter_id: string | null;
          content: string | null;
          created_at: string | null;
          downvotes: number | null;
          id: string | null;
          is_mine: boolean | null;
          parent_id: string | null;
          post_id: string | null;
          rank: number | null;
          upvote: boolean | null;
          upvotes: number | null;
          views: number | null;
        };
        Relationships: [
          {
            foreignKeyName: "comments_parent_id_fkey";
            columns: ["parent_id"];
            isOneToOne: false;
            referencedRelation: "comments";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "comments_parent_id_fkey";
            columns: ["parent_id"];
            isOneToOne: false;
            referencedRelation: "personalized_comments";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "comments_post_id_fkey";
            columns: ["post_id"];
            isOneToOne: false;
            referencedRelation: "posts";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "comments_post_id_fkey";
            columns: ["post_id"];
            isOneToOne: false;
            referencedRelation: "personalized_posts";
            referencedColumns: ["id"];
          },
        ];
      };
      personalized_posts: {
        Row: {
          aspect_ratio: number | null;
          blur_hash: string | null;
          comments: number | null;
          content: string | null;
          created_at: string | null;
          distance: number | null;
          downvotes: number | null;
          has_media: boolean | null;
          id: string | null;
          is_mine: boolean | null;
          poster_color: string | null;
          poster_emoji: string | null;
          poster_id: string | null;
          rank: number | null;
          upvote: boolean | null;
          upvotes: number | null;
          views: number | null;
        };
        Relationships: [];
      };
    };
    Functions: {
      calculate_rank: {
        Args: {
          _distance: number;
          _score: number;
          _created_at: string;
        };
        Returns: number;
      };
      delete_account: {
        Args: Record<PropertyKey, never>;
        Returns: undefined;
      };
      distance_to: {
        Args: {
          _other_location: unknown;
        };
        Returns: number;
      };
    };
    Enums: {
      [_ in never]: never;
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
};

type PublicSchema = Database[Extract<keyof Database, "public">];

export type Tables<
  PublicTableNameOrOptions extends
    | keyof (PublicSchema["Tables"] & PublicSchema["Views"])
    | {schema: keyof Database},
  TableName extends PublicTableNameOrOptions extends {schema: keyof Database}
    ? keyof (Database[PublicTableNameOrOptions["schema"]]["Tables"] &
        Database[PublicTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = PublicTableNameOrOptions extends {schema: keyof Database}
  ? (Database[PublicTableNameOrOptions["schema"]]["Tables"] &
      Database[PublicTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R;
    }
    ? R
    : never
  : PublicTableNameOrOptions extends keyof (PublicSchema["Tables"] &
        PublicSchema["Views"])
    ? (PublicSchema["Tables"] &
        PublicSchema["Views"])[PublicTableNameOrOptions] extends {
        Row: infer R;
      }
      ? R
      : never
    : never;

export type TablesInsert<
  PublicTableNameOrOptions extends
    | keyof PublicSchema["Tables"]
    | {schema: keyof Database},
  TableName extends PublicTableNameOrOptions extends {schema: keyof Database}
    ? keyof Database[PublicTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = PublicTableNameOrOptions extends {schema: keyof Database}
  ? Database[PublicTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I;
    }
    ? I
    : never
  : PublicTableNameOrOptions extends keyof PublicSchema["Tables"]
    ? PublicSchema["Tables"][PublicTableNameOrOptions] extends {
        Insert: infer I;
      }
      ? I
      : never
    : never;

export type TablesUpdate<
  PublicTableNameOrOptions extends
    | keyof PublicSchema["Tables"]
    | {schema: keyof Database},
  TableName extends PublicTableNameOrOptions extends {schema: keyof Database}
    ? keyof Database[PublicTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = PublicTableNameOrOptions extends {schema: keyof Database}
  ? Database[PublicTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U;
    }
    ? U
    : never
  : PublicTableNameOrOptions extends keyof PublicSchema["Tables"]
    ? PublicSchema["Tables"][PublicTableNameOrOptions] extends {
        Update: infer U;
      }
      ? U
      : never
    : never;

export type Enums<
  PublicEnumNameOrOptions extends
    | keyof PublicSchema["Enums"]
    | {schema: keyof Database},
  EnumName extends PublicEnumNameOrOptions extends {schema: keyof Database}
    ? keyof Database[PublicEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = PublicEnumNameOrOptions extends {schema: keyof Database}
  ? Database[PublicEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : PublicEnumNameOrOptions extends keyof PublicSchema["Enums"]
    ? PublicSchema["Enums"][PublicEnumNameOrOptions]
    : never;
